Fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,10 +14,10 @@ jobs:
             os: ubuntu-latest
             vim_version: 8.2.0037
             glibc_version: 2.15
-          - name: vim-v81-x64
-            os: ubuntu-latest
-            vim_version: 8.1.2414
-            glibc_version: 2.15
+            # - name: vim-v81-x64
+            # - os: ubuntu-latest
+            # - vim_version: 8.1.2414
+            # - glibc_version: 2.15
     runs-on: ${{matrix.os}}
     steps:
       - uses: actions/checkout@v2
@@ -35,6 +35,9 @@ jobs:
         shell: bash
         run: |
           export PATH=~/vim/bin:$PATH
-          export VIM_EXE=vim
-          ./tests/run.sh > /dev/null && echo Success || echo Fail
+          echo '$HOME'
+          ls $HOME
+          ls ./tests
+          # export VIM_EXE=vim
+          # ./tests/run.sh > /dev/null && echo Success || echo Fail
 
